on: [push, pull_request]

name: CI

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [beta, stable, 1.13.0]
        exclude:
          # https://github.com/rust-lang/rust/issues/34674
          - os: macos-latest
            rust: 1.13.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  wasi:
    name: Test WASI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: wasm32-wasi
      - run:
          curl https://wasmtime.dev/install.sh -sSf | bash
      - run:
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
      - uses: actions-rs/cargo@v1
        env:
          CARGO_TARGET_WASM32_WASI_RUNNER: wasmtime
        with:
          command: test
          args: --target wasm32-wasi
